# Generated by Django 3.1.3 on 2020-11-26 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HobnobAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isHobnobAdmin', models.BooleanField(default=False)),
                ('users', models.BooleanField(default=False)),
                ('campaigns', models.BooleanField(default=False)),
                ('profile', models.BooleanField(default=False)),
                ('branding', models.BooleanField(default=False)),
                ('deliverable', models.BooleanField(default=False)),
                ('hashtags', models.BooleanField(default=False)),
                ('calender', models.BooleanField(default=False)),
                ('journey', models.BooleanField(default=False)),
                ('finance', models.BooleanField(default=False)),
                ('service', models.BooleanField(default=False)),
                ('marketing', models.BooleanField(default=False)),
                ('Upload', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
